# Chat Request 的生成时间, 30 秒后过期
CHAT_PENDING_REDIS_TTL = 30
CHAT_PENDING_REDIS_KEY = "chat_pending"

# Redis
REDIS_URL = "redis://echoai123@127.0.0.1:6379/0"

# Snowflake
SNOWFLAKE_DATACENTER_ID = 1
SNOWFLAKE_WORKER_ID = 1

# JWT
JWT_SECRET_KEY = "echoai"
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_EXPIRE_TTL = 60 * 15  # 15 minutes
JWT_REFRESH_TOKEN_EXPIRE_TTL = 60 * 60 * 24 * 7  # 7 days
